### ISSUE TITLE
colocar os autores e justificativa da versao no historico  #issue6

### ISSUE THREAD

**Issue by eduardosilva218** [avaliecursos/java-jsp-avaliecursos#6]
* Colocar os nome dos autor de cada versão no historico.md.
* Colocar uma justificativa do porque foi feito aquilo.

algo como

## 0.0.2
autor: hiagor
justificativa: foi feito tais mudanças para resolver tal problema...
* foi feito isso
* foi feito isso

**Comment by eduardosilva218** [comment]
@hiagorhenriquevieira

**Comment by hiagorhenriquevieira** [comment]
Okay.
